<!-- Add Products Page -->
<?php include_once APP_PATH . '/assets/header.php'; ?>
<div style="margin-left:370px ;width:400px; background-color:aliceblue;border-radius:10px;margin-top:5px" \ class="text-center p-2">
    <h2>Add Products</h2>
    <?php echo $this->tag->form("product/add"); ?>
    <br>
    <p>
        <label for="name" class="col-4"><?php echo $this->locale->_('name'); ?></label>
        <?php echo $this->tag->textField(["name", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="description"><?php echo $this->locale->_('description'); ?></label>
        <?php echo $this->tag->textField(["desc", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="tags"><?php echo $this->locale->_('tags'); ?></label>
        <?php echo $this->tag->textField(["tags", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="price"><?php echo $this->locale->_('price'); ?></label>
        <?php echo $this->tag->numericField(["price", 'class' => 'form-control']); ?>
    </p>
    <p>
        <label for="stock"><?php echo $this->locale->_('stock'); ?></label>
        <?php echo $this->tag->numericField(["stock", 'class' => 'form-control']); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton(["Add", 'class' => 'btn btn-primary']); ?>
    </p>

    </form>
</div>