<?php include_once APP_PATH.'/assets/header.php';?>
<table class="table table-bordered table-striped" >
    <caption>table showing details of the products</caption>
    <thead>
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($data as $key => $value) {
            echo "<tr><td>$value[id]</td><td>$value[name]</td><td>$value[desc]</td><td>$value[tags]</td>
            <td>$value[price]</td><td>$value[stock]</td></tr>";
        }
        ?>
    </tbody>
</table>
